# Generated by Django 2.0.6 on 2018-06-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charbuild', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='title',
            field=models.CharField(max_length=201),
        ),
    ]
