# Generated by Django 2.0.6 on 2018-06-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charbuild', '0003_character1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character1',
        ),
        migrations.AlterField(
            model_name='character',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
